services:
  - type: web
    name: forensicai
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0